### PR TITLE
fix incomplete type bug

### PR DESCRIPTION
**Pull request by FirstLoveLife**
fix compile error in this issue: https://github.com/Morwenn/tight_pair/issues/1

### CODE REVIEW

**Comment by Morwenn** [comment]
I'm closing this pull request since I managed to fix the corresponding bug. I will soon update the whole testsuite thing so that CI passes again.

**Comment by FirstLoveLife** [comment]
CI still doesn't pass

**Comment by Morwenn** [comment]
Yeah, it's linked to the fact that I download Catch2 on-the-fly through CI and back when I set it up it still used the old Catch 1.X. The library changed a bit in the meantime and some changes are not retro-compatible, hence the CI not passing.

I started working on completely rewriting the CMake files to be more modern, but didn't fine the time to finish. The CI should pass again once I'm done with that.

**Comment by Morwenn** [comment]
I finished fixing CMake, Catch2 and Travis stuff: the CI is functional again.

**Comment by FirstLoveLife** [comment]
COOL

**Pull request closed without merging**
